create table if not exists store.items
(
    id              integer generated by default as identity primary key,
    email           varchar,
    title           varchar,
    description     varchar,
    imgPath         varchar,
    price           double
);