create table if not exists store.orders
(
    id              integer generated by default as identity primary key,
    user_id         uuid,
    total_sum       double,
    created_at      timestamp default now()
);

create table if not exists store.order_items
(
    order_id        integer not null,
    item_id         integer not null,
    count           integer,
    constraint pk_order_items primary key (order_id, item_id)
    );

create index if not exists idx_order_items_order_id on store.order_items(order_id);