create table if not exists store.carts
(
    id              integer generated by default as identity primary key,
    user_id         uuid
);

create table if not exists store.cart_items
(
    cart_id         integer not null,
    item_id         integer not null,
    count           integer,
    constraint pk_cart_items primary key (cart_id, item_id)
);

create index if not exists idx_cart_items_cart_id on store.cart_items(cart_id);