openapi: 3.1.1
info:
  title: Showcase Service API
  description: API клиента для сервиса платежей
  version: 1.0.0
servers:
  - url: http://127.0.0.1:8081
    description: payment service

components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: http://localhost:8082/realms/online-store/protocol/openid-connect/token
          scopes:
            profile: Profile scope

paths:
  /api/amount:
    get:
      summary: Получить баланс на счете
      security:
        - oauth2: [ profile ]
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                type: number
                format: double
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /api/purchase:
    post:
      summary: Осуществить платеж
      description: Списание указанной суммы с баланса пользователя
      security:
        - oauth2: [ profile ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: number
                  format: double
                  description: Сумма платежа
      responses:
        '201':
          description: Платеж успешно осуществлен
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Неверный запрос
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string