server:
  port: 8080

spring:
  application:
    name: s5_1_online_store
  datasource:
    url: r2dbc:postgresql://localhost:5432/blogdb
    username: admin
    password: 12345

  sql:
    init:
      mode: always

payment:
  service:
    url: http://127.0.0.1:8081