create schema if not exists store;

create table if not exists store.users
(
    id              uuid primary key default gen_random_uuid(),
    email           varchar
    );

create table if not exists store.items
(
    id              integer generated by default as identity primary key,
    title           varchar,
    description     varchar,
    imgPath         varchar,
    price           double
);

create table if not exists store.carts
(
    id              integer generated by default as identity primary key,
    user_id         uuid
);

create table if not exists store.cart_items
(
    cart_id         integer not null,
    item_id         integer not null,
    count           integer,
    constraint pk_cart_items primary key (cart_id, item_id)
    );

create index if not exists idx_cart_items_cart_id on store.cart_items(cart_id);

create table if not exists store.orders
(
    id              integer generated by default as identity primary key,
    user_id         uuid,
    total_sum       double,
    created_at      timestamp default now()
    );

create table if not exists store.order_items
(
    order_id        integer not null,
    item_id         integer not null,
    count           integer,
    constraint pk_order_items primary key (order_id, item_id)
    );

create index if not exists idx_order_items_order_id on store.order_items(order_id);