openapi: 3.1.1
info:
  title: Payment Service API
  description: API сервиса платежей
  version: 1.0.0
paths:
  /api/amount:
    get:
      summary: Получить баланс на счете
      operationId: getAmount
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                type: number
                format: double
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /api/purchase:
    post:
      summary: Осуществить платеж
      description: Списание указанной суммы с баланса пользователя
      operationId: purchase
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                price:
                  type: number
                  format: double
                  description: Сумма платежа
      responses:
        '201':
          description: Платеж успешно осуществлен
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Неверный запрос
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string